[project]
name = "webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "gunicorn>=25.1.0",
    "numpy>=2.4.2",
    "scipy>=1.17.0",
    "sqlalchemy>=2.0.46",
]
